import { useState } from 'react';
import type { GetTranscriptMessage, GetTranscriptResponse } from '@/lib/messages';
import { formatTimestamp } from '@/lib/transcript/format';
import type { TranscriptFixture } from '@/lib/transcript/sanitize';
import { QuizSection } from './QuizSection';

type State =
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'error'; message: string }
  | { status: 'done'; response: Extract<GetTranscriptResponse, { ok: true }> };

const NOT_ON_YOUTUBE = 'Open a YouTube video page first. If the page was already open, reload it.';

export function DebugTools() {
  const [state, setState] = useState<State>({ status: 'idle' });

  async function loadTranscript() {
    setState({ status: 'loading' });
    try {
      const [tab] = await browser.tabs.query({ active: true, currentWindow: true });
      if (tab?.id === undefined) throw new Error(NOT_ON_YOUTUBE);
      const message: GetTranscriptMessage = { type: 'transcript:get', includeFixture: true };
      const response: GetTranscriptResponse = await browser.tabs
        .sendMessage(tab.id, message)
        .catch(() => ({ ok: false, error: NOT_ON_YOUTUBE }));
      setState(
        response.ok ? { status: 'done', response } : { status: 'error', message: response.error },
      );
    } catch (error) {
      setState({
        status: 'error',
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }

  return (
    <>
      <button type="button" onClick={loadTranscript} disabled={state.status === 'loading'}>
        {state.status === 'loading' ? 'Loading transcript...' : 'Get transcript'}
      </button>

      <div aria-live="polite">
        {state.status === 'error' && <p className="error">{state.message}</p>}
        {state.status === 'done' && <Result response={state.response} />}
      </div>
    </>
  );
}

function Result({ response }: { response: Extract<GetTranscriptResponse, { ok: true }> }) {
  const { video, transcript, attempts, fixture } = response;

  return (
    <>
      <section aria-labelledby="video-heading">
        <h2 id="video-heading">{video.title}</h2>
        <dl>
          <dt>Channel</dt>
          <dd>{video.channelName}</dd>
          <dt>Category</dt>
          <dd>{video.category ?? 'Unknown'}</dd>
          <dt>Duration</dt>
          <dd>{formatTimestamp(video.durationSec * 1000)}</dd>
          <dt>Caption tracks</dt>
          <dd>
            {video.captionTracks.length === 0
              ? 'None'
              : video.captionTracks
                  .map((t) => `${t.languageCode}${t.isAutoGenerated ? ' (auto)' : ''}`)
                  .join(', ')}
          </dd>
        </dl>
      </section>

      <section aria-labelledby="attempts-heading">
        <h2 id="attempts-heading">Retrieval steps</h2>
        <ol className="attempts">
          {attempts.map((attempt, index) => (
            <li key={index} className={attempt.outcome}>
              <strong>{attempt.source}</strong>: {attempt.outcome}
              {attempt.detail && ` (${attempt.detail})`}
            </li>
          ))}
        </ol>
      </section>

      {transcript && <QuizSection video={video} transcript={transcript} />}

      {transcript ? (
        <section aria-labelledby="transcript-heading">
          <h2 id="transcript-heading">
            Transcript: {transcript.segments.length} segments
            {transcript.languageCode && `, ${transcript.languageCode}`}
          </h2>
          <div className="actions">
            <button
              type="button"
              onClick={() =>
                navigator.clipboard.writeText(transcript.segments.map((s) => s.text).join('\n'))
              }
            >
              Copy text
            </button>
            {fixture && (
              <button type="button" onClick={() => downloadFixture(fixture)}>
                Download fixture
              </button>
            )}
          </div>
          <ol className="segments">
            {transcript.segments.map((segment, index) => (
              <li key={index}>
                <time>{formatTimestamp(segment.startMs)}</time> {segment.text}
              </li>
            ))}
          </ol>
        </section>
      ) : (
        <p className="error">No transcript available for this video.</p>
      )}
    </>
  );
}

function downloadFixture(fixture: TranscriptFixture) {
  const blob = new Blob([JSON.stringify(fixture, null, 2)], { type: 'application/json' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${fixture.videoId}.${fixture.kind}.json`;
  link.click();
  URL.revokeObjectURL(link.href);
}
