import type { CaptionTrack } from '@/lib/transcript/types';
import { readText, type YouTubeText } from './text';

export interface VideoInfo {
  videoId: string;
  title: string;
  channelId: string;
  channelName: string;
  durationSec: number;
  category?: string;
  isLive: boolean;
  captionTracks: CaptionTrack[];
}

interface PlayerResponse {
  videoDetails?: {
    videoId?: string;
    title?: string;
    channelId?: string;
    author?: string;
    lengthSeconds?: string;
    isLiveContent?: boolean;
    isLive?: boolean;
  };
  microformat?: { playerMicroformatRenderer?: { category?: string } };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: {
        baseUrl?: string;
        languageCode?: string;
        name?: YouTubeText;
        kind?: string;
      }[];
    };
  };
}

export function extractVideoInfo(playerResponse: unknown): VideoInfo | null {
  const response = playerResponse as PlayerResponse | null;
  const details = response?.videoDetails;
  if (!details?.videoId) return null;

  const rawTracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const captionTracks: CaptionTrack[] = rawTracks
    .filter((track) => track.baseUrl && track.languageCode)
    .map((track) => ({
      baseUrl: track.baseUrl!,
      languageCode: track.languageCode!,
      name: readText(track.name) || track.languageCode!,
      isAutoGenerated: track.kind === 'asr',
    }));

  return {
    videoId: details.videoId,
    title: details.title ?? '',
    channelId: details.channelId ?? '',
    channelName: details.author ?? '',
    durationSec: Number(details.lengthSeconds) || 0,
    category: response?.microformat?.playerMicroformatRenderer?.category,
    isLive: details.isLive === true,
    captionTracks,
  };
}

export function videoIdFromUrl(href: string): string | null {
  const url = new URL(href);
  return url.pathname === '/watch' ? url.searchParams.get('v') : null;
}
