import type { VideoInfo } from '@/lib/youtube/player-response';
import { parseGetTranscriptResponse } from './get-transcript';
import { parseJson3 } from './json3';
import { requiresPoToken, selectTrack, toJson3Url } from './tracks';
import type {
  CapturedResponse,
  Transcript,
  TranscriptAttempt,
  TranscriptSegment,
  TranscriptSource,
} from './types';

export interface PanelReadResult {
  captured: CapturedResponse | null;
  segments: TranscriptSegment[];
}

export interface TranscriptDeps {
  preferredLanguages: readonly string[];
  getCaptured(videoId: string): Promise<CapturedResponse[]>;
  fetchText(url: string): Promise<{ status: number; text: string }>;
  readTranscriptPanel(videoId: string): Promise<PanelReadResult>;
}

export interface TranscriptResult {
  transcript: Transcript | null;
  attempts: TranscriptAttempt[];
  /** Raw response the transcript was parsed from, kept for fixture export. */
  raw?: CapturedResponse;
}

export async function getTranscript(
  video: VideoInfo,
  deps: TranscriptDeps,
): Promise<TranscriptResult> {
  const attempts: TranscriptAttempt[] = [];
  const track = selectTrack(video.captionTracks, deps.preferredLanguages);

  const succeed = (
    source: TranscriptSource,
    segments: TranscriptSegment[],
    raw?: CapturedResponse,
    details: Pick<Transcript, 'languageCode' | 'isAutoGenerated'> = {},
  ): TranscriptResult => {
    attempts.push({ source, outcome: 'ok', detail: `${segments.length} segments` });
    return { transcript: { videoId: video.videoId, source, segments, ...details }, attempts, raw };
  };

  const tryParse = (
    source: TranscriptSource,
    captured: CapturedResponse | undefined | null,
    parse: (body: string) => TranscriptSegment[],
  ): TranscriptSegment[] | null => {
    if (!captured) {
      attempts.push({ source, outcome: 'skipped', detail: 'No captured response' });
      return null;
    }
    if (captured.status !== 200) {
      attempts.push({ source, outcome: 'failed', detail: `HTTP ${captured.status}` });
      return null;
    }
    if (!captured.body) {
      attempts.push({
        source,
        outcome: 'failed',
        detail: 'Empty response body (attestation likely failed)',
      });
      return null;
    }
    try {
      const segments = parse(captured.body);
      if (segments.length > 0) return segments;
      attempts.push({ source, outcome: 'failed', detail: 'Response contained no segments' });
    } catch (error) {
      attempts.push({ source, outcome: 'failed', detail: errorMessage(error) });
    }
    return null;
  };

  const captured = await deps.getCaptured(video.videoId);
  const capturedTranscript = pickCapture(captured.filter((c) => c.kind === 'get_transcript'));
  const transcriptSegments = tryParse(
    'captured-transcript',
    capturedTranscript,
    parseGetTranscriptResponse,
  );
  if (transcriptSegments)
    return succeed('captured-transcript', transcriptSegments, capturedTranscript);

  const preferredCaptions = pickCapture(
    captured.filter((c) => c.kind === 'timedtext'),
    track?.languageCode,
  );
  const captionSegments = tryParse('captured-captions', preferredCaptions, parseJson3);
  if (captionSegments) {
    return succeed('captured-captions', captionSegments, preferredCaptions, {
      languageCode: preferredCaptions!.languageCode,
    });
  }

  if (!track) {
    attempts.push({
      source: 'caption-track',
      outcome: 'skipped',
      detail: 'Video has no caption tracks',
    });
  } else if (requiresPoToken(track.baseUrl)) {
    attempts.push({
      source: 'caption-track',
      outcome: 'skipped',
      detail: 'Caption URL requires a proof-of-origin token',
    });
  } else {
    const url = toJson3Url(track.baseUrl);
    try {
      const response = await deps.fetchText(url);
      const raw: CapturedResponse = {
        kind: 'timedtext',
        videoId: video.videoId,
        languageCode: track.languageCode,
        url,
        status: response.status,
        body: response.text,
        capturedAt: Date.now(),
      };
      const segments = tryParse('caption-track', raw, parseJson3);
      if (segments) {
        return succeed('caption-track', segments, raw, {
          languageCode: track.languageCode,
          isAutoGenerated: track.isAutoGenerated,
        });
      }
    } catch (error) {
      attempts.push({ source: 'caption-track', outcome: 'failed', detail: errorMessage(error) });
    }
  }

  let panel: PanelReadResult;
  try {
    panel = await deps.readTranscriptPanel(video.videoId);
  } catch (error) {
    const detail = errorMessage(error);
    attempts.push({ source: 'transcript-panel', outcome: 'failed', detail });
    attempts.push({
      source: 'panel-dom',
      outcome: 'skipped',
      detail: 'Transcript panel unavailable',
    });
    return { transcript: null, attempts };
  }

  const panelParser =
    panel.captured?.kind === 'timedtext' ? parseJson3 : parseGetTranscriptResponse;
  const panelSegments = tryParse('transcript-panel', panel.captured, panelParser);
  if (panelSegments) {
    return succeed('transcript-panel', panelSegments, panel.captured!, {
      languageCode: panel.captured!.languageCode,
    });
  }

  if (panel.segments.length > 0) return succeed('panel-dom', panel.segments);
  attempts.push({
    source: 'panel-dom',
    outcome: 'failed',
    detail: 'No transcript segments found in the page',
  });

  return { transcript: null, attempts };
}

/** Prefers usable responses, then the requested language, then the most recent. */
function pickCapture(
  captures: CapturedResponse[],
  languageCode?: string,
): CapturedResponse | undefined {
  const usable = captures.filter((c) => c.status === 200 && c.body);
  const pool = usable.length > 0 ? usable : captures;
  return pool.findLast((c) => c.languageCode === languageCode) ?? pool.at(-1);
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
