import type { CaptionTrack } from './types';

const YOUTUBE_ORIGIN = 'https://www.youtube.com';

export function selectTrack(
  tracks: readonly CaptionTrack[],
  preferredLanguages: readonly string[],
): CaptionTrack | undefined {
  const rank = (track: CaptionTrack) =>
    languageRank(track.languageCode, preferredLanguages) * 2 + (track.isAutoGenerated ? 1 : 0);
  return [...tracks].sort((a, b) => rank(a) - rank(b))[0];
}

function languageRank(code: string, preferred: readonly string[]): number {
  const normalized = code.toLowerCase();
  const base = normalized.split('-')[0];
  for (const [i, language] of preferred.entries()) {
    const candidate = language.toLowerCase();
    if (candidate === normalized) return i * 2;
    if (candidate.split('-')[0] === base) return i * 2 + 1;
  }
  return preferred.length * 2;
}

/** Caption URLs flagged with `exp=xpe` return an empty body without a player-minted `pot` token. */
export function requiresPoToken(baseUrl: string): boolean {
  const experiments = new URL(baseUrl, YOUTUBE_ORIGIN).searchParams.get('exp');
  return experiments?.split(',').includes('xpe') ?? false;
}

export function toJson3Url(baseUrl: string): string {
  const url = new URL(baseUrl, YOUTUBE_ORIGIN);
  url.searchParams.set('fmt', 'json3');
  return url.toString();
}
