export interface TranscriptSegment {
  startMs: number;
  durationMs: number;
  text: string;
}

export type TranscriptSource =
  'captured-transcript' | 'captured-captions' | 'caption-track' | 'transcript-panel' | 'panel-dom';

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface Transcript {
  videoId: string;
  source: TranscriptSource;
  languageCode?: string;
  isAutoGenerated?: boolean;
  segments: TranscriptSegment[];
}

export interface TranscriptAttempt {
  source: TranscriptSource;
  outcome: 'ok' | 'skipped' | 'failed';
  detail?: string;
}

export type CapturedKind = 'get_transcript' | 'timedtext';

export interface CapturedResponse {
  kind: CapturedKind;
  videoId: string;
  languageCode?: string;
  url: string;
  status: number;
  body: string;
  capturedAt: number;
}
