import { readFileSync } from 'node:fs';
import { describe, expect, it, vi } from 'vitest';
import { getTranscript, type TranscriptDeps } from '@/lib/transcript/pipeline';
import type { CapturedResponse } from '@/lib/transcript/types';
import type { VideoInfo } from '@/lib/youtube/player-response';

const fixture = (name: string) =>
  readFileSync(new URL(`./fixtures/synthetic/${name}`, import.meta.url), 'utf8');

const GET_TRANSCRIPT_BODY = fixture('get-transcript.json');
const JSON3_BODY = fixture('json3-manual.json');

const video = (baseUrl = '/api/timedtext?v=vid&lang=en'): VideoInfo => ({
  videoId: 'vid',
  title: 'Title',
  channelId: 'channel',
  channelName: 'Channel',
  durationSec: 600,
  category: 'Education',
  isLive: false,
  captionTracks: [{ baseUrl, languageCode: 'en', name: 'English', isAutoGenerated: false }],
});

const capture = (overrides: Partial<CapturedResponse>): CapturedResponse => ({
  kind: 'get_transcript',
  videoId: 'vid',
  url: '/youtubei/v1/get_transcript',
  status: 200,
  body: GET_TRANSCRIPT_BODY,
  capturedAt: 1,
  ...overrides,
});

const deps = (overrides: Partial<TranscriptDeps> = {}): TranscriptDeps => ({
  preferredLanguages: ['en'],
  getCaptured: vi.fn(async () => []),
  fetchText: vi.fn(async () => ({ status: 200, text: '' })),
  readTranscriptPanel: vi.fn(async () => ({ captured: null, segments: [] })),
  ...overrides,
});

const outcomes = (result: Awaited<ReturnType<typeof getTranscript>>) =>
  result.attempts.map((a) => `${a.source}:${a.outcome}`);

describe('getTranscript', () => {
  it('uses a captured get_transcript response without any other requests', async () => {
    const d = deps({ getCaptured: async () => [capture({})] });
    const result = await getTranscript(video(), d);

    expect(result.transcript?.source).toBe('captured-transcript');
    expect(result.transcript?.segments).toHaveLength(3);
    expect(result.raw?.kind).toBe('get_transcript');
    expect(d.fetchText).not.toHaveBeenCalled();
    expect(d.readTranscriptPanel).not.toHaveBeenCalled();
  });

  it('uses captured captions, preferring a usable response in the selected language', async () => {
    const d = deps({
      getCaptured: async () => [
        capture({ kind: 'timedtext', languageCode: 'en', body: JSON3_BODY, capturedAt: 1 }),
        capture({ kind: 'timedtext', languageCode: 'en', body: '', capturedAt: 2 }),
        capture({ kind: 'timedtext', languageCode: 'de', body: JSON3_BODY, capturedAt: 3 }),
      ],
    });
    const result = await getTranscript(video(), d);

    expect(result.transcript).toMatchObject({ source: 'captured-captions', languageCode: 'en' });
    expect(outcomes(result)).toEqual(['captured-transcript:skipped', 'captured-captions:ok']);
  });

  it('fetches the caption track directly when it does not need a token', async () => {
    const fetchText = vi.fn(async () => ({ status: 200, text: JSON3_BODY }));
    const result = await getTranscript(video(), deps({ fetchText }));

    expect(fetchText).toHaveBeenCalledWith(
      'https://www.youtube.com/api/timedtext?v=vid&lang=en&fmt=json3',
    );
    expect(result.transcript).toMatchObject({
      source: 'caption-track',
      languageCode: 'en',
      isAutoGenerated: false,
    });
  });

  it('skips the direct fetch for exp=xpe tracks and opens the panel', async () => {
    const d = deps({
      readTranscriptPanel: async () => ({ captured: capture({ capturedAt: 5 }), segments: [] }),
    });
    const result = await getTranscript(video('/api/timedtext?v=vid&lang=en&exp=xpe'), d);

    expect(d.fetchText).not.toHaveBeenCalled();
    expect(result.transcript?.source).toBe('transcript-panel');
    expect(outcomes(result)).toEqual([
      'captured-transcript:skipped',
      'captured-captions:skipped',
      'caption-track:skipped',
      'transcript-panel:ok',
    ]);
  });

  it('parses a caption response captured while the panel was open', async () => {
    const d = deps({
      readTranscriptPanel: async () => ({
        captured: capture({ kind: 'timedtext', languageCode: 'en', body: JSON3_BODY }),
        segments: [],
      }),
    });
    const result = await getTranscript(video('/api/timedtext?v=vid&exp=xpe'), d);
    expect(result.transcript).toMatchObject({ source: 'transcript-panel', languageCode: 'en' });
  });

  it('falls back to scraped panel segments when the captured response failed', async () => {
    const segments = [{ startMs: 0, durationMs: 1000, text: 'Scraped' }];
    const d = deps({
      fetchText: async () => ({ status: 200, text: '' }),
      readTranscriptPanel: async () => ({
        captured: capture({ status: 400, body: fixture('get-transcript-error.json') }),
        segments,
      }),
    });
    const result = await getTranscript(video(), d);

    expect(result.transcript).toMatchObject({ source: 'panel-dom', segments });
    expect(result.raw).toBeUndefined();
    expect(result.attempts).toContainEqual({
      source: 'caption-track',
      outcome: 'failed',
      detail: 'Empty response body (attestation likely failed)',
    });
    expect(result.attempts).toContainEqual({
      source: 'transcript-panel',
      outcome: 'failed',
      detail: 'HTTP 400',
    });
  });

  it('reports every failed step when nothing works', async () => {
    const d = deps({
      getCaptured: async () => [capture({ kind: 'timedtext', body: '' })],
      fetchText: async () => {
        throw new Error('Network down');
      },
    });
    const result = await getTranscript(video(), d);

    expect(result.transcript).toBeNull();
    expect(outcomes(result)).toEqual([
      'captured-transcript:skipped',
      'captured-captions:failed',
      'caption-track:failed',
      'transcript-panel:skipped',
      'panel-dom:failed',
    ]);
  });

  it('handles videos without caption tracks or a transcript panel', async () => {
    const d = deps({
      readTranscriptPanel: async () => {
        throw new Error('Transcript panel not found on the page');
      },
    });
    const result = await getTranscript({ ...video(), captionTracks: [] }, d);

    expect(result.transcript).toBeNull();
    expect(result.attempts.slice(2)).toEqual([
      { source: 'caption-track', outcome: 'skipped', detail: 'Video has no caption tracks' },
      {
        source: 'transcript-panel',
        outcome: 'failed',
        detail: 'Transcript panel not found on the page',
      },
      { source: 'panel-dom', outcome: 'skipped', detail: 'Transcript panel unavailable' },
    ]);
  });

  it('reports malformed captured responses instead of throwing', async () => {
    const d = deps({ getCaptured: async () => [capture({ body: '<html>' })] });
    const result = await getTranscript(video('/api/timedtext?v=vid&exp=xpe'), d);
    expect(result.attempts[0]).toMatchObject({ source: 'captured-transcript', outcome: 'failed' });
  });
});
