import { describe, expect, it } from 'vitest';
import { formatTimestamp } from '@/lib/transcript/format';
import { toFixture } from '@/lib/transcript/sanitize';
import { extractVideoInfo, videoIdFromUrl } from '@/lib/youtube/player-response';

describe('extractVideoInfo', () => {
  it('extracts metadata and caption tracks', () => {
    const info = extractVideoInfo({
      videoDetails: {
        videoId: 'aircAruvnKk',
        title: 'But what is a neural network?',
        channelId: 'UCYO_jab_esuFRV4b17AJtAw',
        author: '3Blue1Brown',
        lengthSeconds: '1143',
        isLiveContent: false,
      },
      microformat: { playerMicroformatRenderer: { category: 'Education' } },
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              baseUrl: '/api/timedtext?lang=en',
              languageCode: 'en',
              name: { simpleText: 'English' },
            },
            {
              baseUrl: '/api/timedtext?lang=en&kind=asr',
              languageCode: 'en',
              name: { runs: [{ text: 'English (auto-generated)' }] },
              kind: 'asr',
            },
            { languageCode: 'fr', name: { simpleText: 'Missing URL' } },
          ],
        },
      },
    });

    expect(info).toEqual({
      videoId: 'aircAruvnKk',
      title: 'But what is a neural network?',
      channelId: 'UCYO_jab_esuFRV4b17AJtAw',
      channelName: '3Blue1Brown',
      durationSec: 1143,
      category: 'Education',
      isLive: false,
      captionTracks: [
        {
          baseUrl: '/api/timedtext?lang=en',
          languageCode: 'en',
          name: 'English',
          isAutoGenerated: false,
        },
        {
          baseUrl: '/api/timedtext?lang=en&kind=asr',
          languageCode: 'en',
          name: 'English (auto-generated)',
          isAutoGenerated: true,
        },
      ],
    });
  });

  it('returns null without video details', () => {
    expect(extractVideoInfo(null)).toBeNull();
    expect(extractVideoInfo({ playabilityStatus: { status: 'ERROR' } })).toBeNull();
  });

  it('tolerates missing optional fields', () => {
    expect(extractVideoInfo({ videoDetails: { videoId: 'abc' } })).toMatchObject({
      videoId: 'abc',
      durationSec: 0,
      category: undefined,
      captionTracks: [],
    });
  });
});

describe('videoIdFromUrl', () => {
  it('reads the v parameter on watch pages only', () => {
    expect(videoIdFromUrl('https://www.youtube.com/watch?v=abc&t=10')).toBe('abc');
    expect(videoIdFromUrl('https://www.youtube.com/shorts/abc')).toBeNull();
    expect(videoIdFromUrl('https://www.youtube.com/')).toBeNull();
  });
});

describe('toFixture', () => {
  it('removes tracking data, visitor data, URLs, and IP addresses', () => {
    const fixture = toFixture({
      kind: 'get_transcript',
      videoId: 'abc',
      url: 'https://www.youtube.com/youtubei/v1/get_transcript?pot=SECRET',
      status: 200,
      capturedAt: Date.UTC(2026, 9, 2),
      body: JSON.stringify({
        responseContext: { visitorData: 'SECRET' },
        actions: [
          {
            clickTrackingParams: 'SECRET',
            text: 'Served to 217.155.144.66',
            nested: { visitorData: 'SECRET', keep: 1 },
          },
        ],
      }),
    });

    expect(fixture).toEqual({
      videoId: 'abc',
      kind: 'get_transcript',
      languageCode: undefined,
      capturedAt: '2026-10-02T00:00:00.000Z',
      video: undefined,
      body: { actions: [{ text: 'Served to 0.0.0.0', nested: { keep: 1 } }] },
    });
    expect(JSON.stringify(fixture)).not.toContain('SECRET');
  });
});

describe('formatTimestamp', () => {
  it.each([
    [0, '0:00'],
    [65_400, '1:05'],
    [3_723_000, '1:02:03'],
  ])('formats %d ms as %s', (ms, expected) => {
    expect(formatTimestamp(ms)).toBe(expected);
  });
});
