import { describe, expect, it } from 'vitest';
import { ACTIVITY_TYPES } from '@/lib/learn/schema';
import {
  channelRule,
  checkEligibility,
  DEFAULT_PROMPT_SETTINGS,
  enabledActivityTypes,
  prepareAtSec,
  withChannelRule,
  type PromptSettings,
} from '@/lib/prompt-settings';

const CHANNEL = { id: 'UC123', name: 'Science Channel' };

const video = (overrides: Partial<Parameters<typeof checkEligibility>[0]> = {}) => ({
  channelId: CHANNEL.id,
  category: 'Education',
  durationSec: 600,
  isLive: false,
  captionTracks: [{ baseUrl: '/t', languageCode: 'en', name: 'English', isAutoGenerated: false }],
  ...overrides,
});

const settings = (overrides: Partial<PromptSettings> = {}): PromptSettings => ({
  ...DEFAULT_PROMPT_SETTINGS,
  ...overrides,
});

describe('checkEligibility', () => {
  it('offers quizzes for Education videos by default', () => {
    expect(checkEligibility(video(), settings())).toEqual({
      eligible: true,
      reason: 'This is an Education video.',
    });
  });

  it.each([
    [
      'automatic quizzes are off',
      video(),
      settings({ autoPrompt: false }),
      'The Learn button is turned off for Education videos.',
    ],
    [
      'the channel is blocked',
      video(),
      settings({ blockedChannels: [CHANNEL] }),
      'The Learn button is turned off for this channel.',
    ],
    ['the video is live', video({ isLive: true }), settings(), 'Live streams are not supported.'],
    [
      'the video is short',
      video({ durationSec: 179 }),
      settings(),
      'The video is shorter than 3 minutes.',
    ],
    [
      'there are no captions',
      video({ captionTracks: [] }),
      settings(),
      'The video has no captions.',
    ],
    [
      'the category is not Education',
      video({ category: 'Entertainment' }),
      settings(),
      'The video is not in the Education category.',
    ],
  ])('declines when %s', (_, v, s, reason) => {
    expect(checkEligibility(v, s)).toEqual({ eligible: false, reason });
  });

  it('offers quizzes for allowed channels in any category', () => {
    expect(
      checkEligibility(video({ category: 'Gaming' }), settings({ allowedChannels: [CHANNEL] })),
    ).toEqual({ eligible: true, reason: 'The Learn button is always on for this channel.' });
  });

  it('still requires captions and a minimum length for allowed channels', () => {
    const allowed = settings({ allowedChannels: [CHANNEL] });
    expect(checkEligibility(video({ durationSec: 60 }), allowed).eligible).toBe(false);
    expect(checkEligibility(video({ captionTracks: [] }), allowed).eligible).toBe(false);
  });
});

describe('channel rules', () => {
  it('moves a channel between lists without duplicates', () => {
    let s = withChannelRule(settings(), CHANNEL, 'always');
    expect(channelRule(s, CHANNEL.id)).toBe('always');
    s = withChannelRule(s, CHANNEL, 'always');
    expect(s.allowedChannels).toEqual([CHANNEL]);

    s = withChannelRule(s, CHANNEL, 'never');
    expect(s.allowedChannels).toEqual([]);
    expect(s.blockedChannels).toEqual([CHANNEL]);
    expect(channelRule(s, CHANNEL.id)).toBe('never');

    s = withChannelRule(s, CHANNEL, 'auto');
    expect(s).toEqual(settings());
    expect(channelRule(s, CHANNEL.id)).toBe('auto');
  });
});

describe('prepareAtSec', () => {
  it('starts background preparation halfway through', () => {
    expect(prepareAtSec(180)).toBe(90);
    expect(prepareAtSec(3600)).toBe(1800);
  });
});

describe('enabledActivityTypes', () => {
  it('returns all types by default and for settings saved before types existed', () => {
    expect(enabledActivityTypes(settings())).toEqual([...ACTIVITY_TYPES]);
    const { disabledActivityTypes: _omitted, ...legacy } = settings();
    expect(enabledActivityTypes(legacy)).toEqual([...ACTIVITY_TYPES]);
  });

  it('leaves out disabled types, but never returns none', () => {
    expect(
      enabledActivityTypes(settings({ disabledActivityTypes: ['ordering', 'cloze'] })),
    ).toEqual(ACTIVITY_TYPES.filter((t) => t !== 'ordering' && t !== 'cloze'));
    expect(enabledActivityTypes(settings({ disabledActivityTypes: [...ACTIVITY_TYPES] }))).toEqual([
      ...ACTIVITY_TYPES,
    ]);
  });
});
