import { describe, expect, it } from 'vitest';
import { requiresPoToken, selectTrack, toJson3Url } from '@/lib/transcript/tracks';
import type { CaptionTrack } from '@/lib/transcript/types';

const track = (languageCode: string, isAutoGenerated = false): CaptionTrack => ({
  baseUrl: `https://www.youtube.com/api/timedtext?v=abc&lang=${languageCode}`,
  languageCode,
  name: languageCode,
  isAutoGenerated,
});

describe('selectTrack', () => {
  it('prefers manual captions over auto-generated in the same language', () => {
    expect(selectTrack([track('en', true), track('en')], ['en'])).toEqual(track('en'));
  });

  it('prefers an exact regional match, then the base language', () => {
    const tracks = [track('en'), track('en-GB'), track('fr')];
    expect(selectTrack(tracks, ['en-GB', 'en'])?.languageCode).toBe('en-GB');
    expect(selectTrack(tracks, ['en-US'])?.languageCode).toBe('en');
  });

  it('follows the order of preferred languages', () => {
    expect(selectTrack([track('en'), track('de')], ['de', 'en'])?.languageCode).toBe('de');
  });

  it('prefers an auto track in a preferred language over a manual track in another', () => {
    expect(selectTrack([track('fr'), track('en', true)], ['en'])?.languageCode).toBe('en');
  });

  it('falls back to the first manual track when nothing matches', () => {
    expect(selectTrack([track('ja', true), track('ko')], ['en'])?.languageCode).toBe('ko');
  });

  it('returns undefined when there are no tracks', () => {
    expect(selectTrack([], ['en'])).toBeUndefined();
  });
});

describe('requiresPoToken', () => {
  it('detects the xpe experiment flag', () => {
    expect(requiresPoToken('https://www.youtube.com/api/timedtext?v=a&exp=xpe')).toBe(true);
    expect(requiresPoToken('/api/timedtext?v=a&exp=xpv,xpe')).toBe(true);
    expect(requiresPoToken('/api/timedtext?v=a&exp=xpv')).toBe(false);
    expect(requiresPoToken('/api/timedtext?v=a')).toBe(false);
  });
});

describe('toJson3Url', () => {
  it('sets fmt=json3, replacing any existing format', () => {
    const url = new URL(toJson3Url('/api/timedtext?v=a&fmt=srv3&lang=en'));
    expect(url.origin).toBe('https://www.youtube.com');
    expect(url.searchParams.get('fmt')).toBe('json3');
    expect(url.searchParams.get('lang')).toBe('en');
  });
});
