import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { CachedActivities } from '@/lib/db';
import { DEFAULT_PROMPT_SETTINGS, type PromptSettings } from '@/lib/prompt-settings';
import { Store, WatchSession, type OverlayState, type WatchDeps } from '@/lib/watch/session';
import type { VideoInfo } from '@/lib/youtube/player-response';

const VIDEO: VideoInfo = {
  videoId: 'vid',
  title: 'Title',
  channelId: 'UC1',
  channelName: 'Channel',
  durationSec: 600,
  category: 'Education',
  isLive: false,
  captionTracks: [{ baseUrl: '/t', languageCode: 'en', name: 'English', isAutoGenerated: false }],
};

const QUIZ: CachedActivities = {
  videoId: 'vid',
  title: 'Title',
  set: {
    topic: 'Biology',
    activities: [
      {
        type: 'recall',
        prompt: 'Q?',
        answer: 'A.',
        explanation: '',
        options: [],
        sourceStartSec: 5,
      },
      {
        type: 'cloze',
        prompt: 'A ____.',
        answer: 'x',
        explanation: '',
        options: [],
        sourceStartSec: 9,
      },
    ],
  },
  providerId: 'custom',
  model: 'm',
  createdAt: 1,
};

const LEARN_VIEW: OverlayState = {
  view: 'learn',
  entry: QUIZ,
  activities: QUIZ.set.activities,
  video: { id: 'vid', title: 'Title', channelId: 'UC1', channelName: 'Channel', durationSec: 600 },
};

const SEGMENTS = [{ startMs: 0, durationMs: 1000, text: 'hello' }];

type GenerateResult = Awaited<ReturnType<WatchDeps['generateQuiz']>>;

const flush = () => new Promise((resolve) => setTimeout(resolve, 0));

let overlay: Store<OverlayState>;
let deps: { [K in keyof WatchDeps]: ReturnType<typeof vi.fn> } & WatchDeps;

function session(prefs: Partial<PromptSettings> = {}, video: Partial<VideoInfo> = {}) {
  deps.loadPrefs.mockResolvedValue({ ...DEFAULT_PROMPT_SETTINGS, ...prefs });
  deps.loadVideo.mockResolvedValue({ ...VIDEO, ...video });
  return new WatchSession('vid', deps, overlay);
}

function deferredGeneration() {
  let finish!: (value: GenerateResult) => void;
  deps.generateQuiz.mockReturnValueOnce(
    new Promise<GenerateResult>((resolve) => (finish = resolve)),
  );
  return (value: GenerateResult = { ok: true, quiz: QUIZ, cached: false }) => finish(value);
}

beforeEach(() => {
  overlay = new Store<OverlayState>({ view: 'hidden' });
  deps = {
    loadVideo: vi.fn(),
    loadPrefs: vi.fn(),
    getCachedQuiz: vi.fn(async () => null),
    loadTranscript: vi.fn(async () => SEGMENTS),
    generateQuiz: vi.fn(async () => ({ ok: true as const, quiz: QUIZ, cached: false })),
    askQuestion: vi.fn(async () => ({ ok: true as const, answer: 'Because.' })),
    currentSec: vi.fn(() => 75.6),
    pauseVideo: vi.fn(),
    onStatus: vi.fn(),
    log: vi.fn(),
  } as typeof deps;
});

describe('WatchSession background preparation', () => {
  it('prepares once at 50% without showing anything on the video', async () => {
    const s = session();
    await s.start();

    s.onProgress(299);
    await flush();
    expect(deps.getCachedQuiz).not.toHaveBeenCalled();

    for (const second of [300, 301, 550, 599]) s.onProgress(second);
    await flush();
    expect(deps.loadTranscript).toHaveBeenCalledOnce();
    expect(deps.generateQuiz).toHaveBeenCalledWith(
      expect.objectContaining({ videoId: 'vid' }),
      SEGMENTS,
    );
    expect(overlay.get().view).toBe('hidden');
    expect(s.getStatus()).toEqual({ state: 'ready', activityCount: 2 });
  });

  it('uses a cached quiz without loading the transcript', async () => {
    deps.getCachedQuiz.mockResolvedValueOnce(QUIZ);
    const s = session();
    await s.start();
    s.onProgress(300);
    await flush();
    expect(deps.loadTranscript).not.toHaveBeenCalled();
    expect(s.getStatus()).toEqual({ state: 'ready', activityCount: 2 });
  });

  it('does nothing for ineligible videos', async () => {
    const s = session({}, { category: 'Music' });
    await s.start();
    s.onProgress(590);
    await flush();
    expect(deps.getCachedQuiz).not.toHaveBeenCalled();
  });

  it('tries once, then reports and logs the failure', async () => {
    deps.loadTranscript.mockResolvedValue(null);
    const s = session();
    await s.start();
    for (const second of [300, 301, 302, 560]) s.onProgress(second);
    await flush();

    expect(deps.loadTranscript).toHaveBeenCalledOnce();
    expect(s.getStatus()).toEqual({
      state: 'failed',
      code: 'no-transcript',
      message: 'No transcript is available for this video.',
    });
    expect(deps.log).toHaveBeenCalledWith(
      'Activity preparation failed (no-transcript): No transcript is available for this video.',
    );
    expect(overlay.get().view).toBe('hidden');
  });

  it('loads the transcript with fresh caption URLs, not those from page load', async () => {
    const s = session();
    await s.start();
    const fresh: VideoInfo = {
      ...VIDEO,
      captionTracks: [
        { baseUrl: '/fresh', languageCode: 'en', name: 'English', isAutoGenerated: false },
      ],
    };
    deps.loadVideo.mockResolvedValue(fresh);
    s.onProgress(300);
    await flush();

    expect(deps.loadTranscript).toHaveBeenCalledWith(fresh);
  });
});

describe('WatchSession status', () => {
  it('reports and emits each stage from loading to ready', async () => {
    const finish = deferredGeneration();
    const s = session();
    expect(s.getStatus()).toEqual({ state: 'loading' });
    await s.start();
    expect(s.getStatus()).toEqual({ state: 'waiting', prepareAtSec: 300 });

    s.onProgress(300);
    await flush();
    expect(s.getStatus()).toEqual({ state: 'preparing', step: 'generating' });

    finish();
    await flush();
    expect(s.getStatus()).toEqual({ state: 'ready', activityCount: 2 });

    const emitted = deps.onStatus.mock.calls.map(([status]) =>
      status.step ? `${status.state}:${status.step}` : status.state,
    );
    expect(emitted).toEqual([
      'loading',
      'waiting',
      'preparing:cache',
      'preparing:transcript',
      'preparing:generating',
      'ready',
    ]);
  });

  it('reports why a video is not eligible', async () => {
    const s = session({}, { category: 'Music' });
    await s.start();
    expect(s.getStatus()).toEqual({
      state: 'not-eligible',
      reason: 'The video is not in the Education category.',
    });
  });

  it('reports when the video details fail to load', async () => {
    deps.loadVideo.mockRejectedValueOnce(new Error('Video details did not load.'));
    deps.loadPrefs.mockResolvedValue(DEFAULT_PROMPT_SETTINGS);
    const s = new WatchSession('vid', deps, overlay);
    await s.start();
    expect(s.getStatus()).toEqual({ state: 'not-eligible', reason: 'Video details did not load.' });
  });

  it('stops emitting after dispose', async () => {
    const s = session();
    s.dispose();
    await s.start();
    expect(deps.onStatus).not.toHaveBeenCalled();
  });
});

describe('WatchSession opening the quiz', () => {
  it('opens a prepared quiz immediately and pauses the video', async () => {
    deps.getCachedQuiz.mockResolvedValue(QUIZ);
    const s = session();
    await s.start();
    s.onProgress(300);
    await flush();
    await s.openNow();
    expect(overlay.get()).toEqual(LEARN_VIEW);
    expect(deps.pauseVideo).toHaveBeenCalledOnce();
  });

  it('generates first for any video, showing loading', async () => {
    const s = session({ autoPrompt: false }, { category: 'Music' });
    const opening = s.openNow();
    expect(overlay.get().view).toBe('loading');
    await opening;
    expect(overlay.get()).toEqual(LEARN_VIEW);
  });

  it('waits for a background generation that is already running', async () => {
    const finish = deferredGeneration();
    const s = session();
    await s.start();
    s.onProgress(300);
    const opening = s.openNow();
    expect(overlay.get().view).toBe('loading');
    finish();
    await opening;
    expect(overlay.get().view).toBe('learn');
    expect(deps.generateQuiz).toHaveBeenCalledOnce();
  });

  it('shows provider errors with their code', async () => {
    deps.generateQuiz.mockResolvedValueOnce({ ok: false, code: 'auth', error: 'Bad key.' });
    const s = session();
    await s.openNow();
    expect(overlay.get()).toEqual({ view: 'error', code: 'auth', message: 'Bad key.' });
  });

  it('retries after a background failure', async () => {
    deps.loadTranscript.mockResolvedValueOnce(null);
    const s = session();
    await s.start();
    s.onProgress(300);
    await flush();
    expect(s.getStatus().state).toBe('failed');

    await s.openNow();
    expect(overlay.get().view).toBe('learn');
    expect(s.getStatus()).toEqual({ state: 'ready', activityCount: 2 });
  });

  it('shows and counts only the activity types enabled in settings', async () => {
    deps.getCachedQuiz.mockResolvedValue(QUIZ);
    const s = session({ disabledActivityTypes: ['cloze'] });
    await s.start();
    s.onProgress(300);
    await flush();
    expect(s.getStatus()).toEqual({ state: 'ready', activityCount: 1 });
    await s.openNow();
    expect(overlay.get()).toMatchObject({ view: 'learn', activities: [QUIZ.set.activities[0]] });
  });

  it('explains instead of opening an empty set', async () => {
    deps.getCachedQuiz.mockResolvedValue({ ...QUIZ, set: { topic: 'T', activities: [] } });
    const s = session();
    await s.openNow();
    expect(overlay.get()).toEqual({
      view: 'error',
      code: 'no-activities',
      message: 'The video has nothing worth learning.',
    });
  });

  it('does not open the quiz if the loading dialog was closed', async () => {
    const s = session();
    const opening = s.openNow();
    s.close();
    await opening;
    expect(overlay.get().view).toBe('hidden');
    expect(deps.pauseVideo).not.toHaveBeenCalled();
  });

  it('stops updating the overlay after dispose', async () => {
    const s = session();
    const opening = s.openNow();
    s.dispose();
    await opening;
    expect(overlay.get().view).toBe('hidden');
  });
});

describe('WatchSession questions', () => {
  it('opens the question dialog, pauses the video, and loads the transcript', async () => {
    const s = session();
    s.openAsk();
    expect(overlay.get()).toEqual({ view: 'ask', conversation: s.conversation });
    expect(deps.pauseVideo).toHaveBeenCalledOnce();
    await flush();
    expect(deps.loadTranscript).toHaveBeenCalledOnce();
  });

  it('sends the conversation with the playback position and keeps the answers', async () => {
    const s = session();
    expect(await s.ask('  Why?  ')).toBe(true);
    expect(deps.askQuestion).toHaveBeenLastCalledWith(
      expect.objectContaining({ videoId: 'vid' }),
      SEGMENTS,
      [{ role: 'user', text: 'Why?', atSec: 75 }],
    );

    deps.askQuestion.mockResolvedValueOnce({ ok: true, answer: 'Like this.' });
    await s.ask('How?');
    expect(deps.askQuestion.mock.calls[1]![2]).toHaveLength(3);
    expect(s.conversation.get()).toEqual({
      turns: [
        { role: 'user', text: 'Why?', atSec: 75 },
        { role: 'assistant', text: 'Because.' },
        { role: 'user', text: 'How?', atSec: 75 },
        { role: 'assistant', text: 'Like this.' },
      ],
      pending: false,
      error: null,
    });
  });

  it('shares one transcript load with activity preparation', async () => {
    const s = session();
    s.openAsk();
    await s.ask('Why?');
    await s.openNow();
    expect(deps.loadTranscript).toHaveBeenCalledOnce();
  });

  it('shows the pending state and ignores questions sent while waiting', async () => {
    let finish!: (value: { ok: true; answer: string }) => void;
    deps.askQuestion.mockReturnValueOnce(new Promise((resolve) => (finish = resolve)));
    const s = session();
    const asking = s.ask('Why?');
    await flush();
    expect(s.conversation.get().pending).toBe(true);
    expect(await s.ask('Again?')).toBe(false);
    finish({ ok: true, answer: 'Because.' });
    await asking;
    expect(s.conversation.get().turns).toHaveLength(2);
  });

  it('drops an unanswered question and reports the error', async () => {
    deps.askQuestion.mockResolvedValueOnce({ ok: false, code: 'auth', error: 'Bad key.' });
    const s = session();
    expect(await s.ask('Why?')).toBe(false);
    expect(s.conversation.get()).toEqual({
      turns: [],
      pending: false,
      error: { code: 'auth', message: 'Bad key.' },
    });
    expect(await s.ask('Why?')).toBe(true);
    expect(s.conversation.get().error).toBeNull();
  });

  it('reports a missing transcript and retries it on the next question', async () => {
    deps.loadTranscript.mockResolvedValueOnce(null);
    const s = session();
    s.openAsk();
    await flush();
    expect(s.conversation.get().error).toEqual({
      code: 'no-transcript',
      message: 'No transcript is available for this video.',
    });
    expect(deps.askQuestion).not.toHaveBeenCalled();

    expect(await s.ask('Why?')).toBe(true);
    expect(deps.loadTranscript).toHaveBeenCalledTimes(2);
  });
});

describe('Store', () => {
  it('notifies subscribers until they unsubscribe', () => {
    const listener = vi.fn();
    const unsubscribe = overlay.subscribe(listener);
    overlay.set({ view: 'loading' });
    unsubscribe();
    overlay.set({ view: 'hidden' });
    expect(listener).toHaveBeenCalledOnce();
  });
});
