import type { CachedActivities } from '@/lib/db';
import type { VideoResult } from '@/lib/knowledge/bank';
import type { ChannelRule, Eligibility } from '@/lib/prompt-settings';
import type { ChatTurn } from '@/lib/learn/ask';
import type { QuizErrorCode } from '@/lib/learn/errors';
import type { TranscriptFixture } from '@/lib/transcript/sanitize';
import type { Transcript, TranscriptAttempt, TranscriptSegment } from '@/lib/transcript/types';
import type { VideoInfo } from '@/lib/youtube/player-response';

export interface GetTranscriptMessage {
  type: 'transcript:get';
  includeFixture?: boolean;
}

export type VideoSummary = Omit<VideoInfo, 'captionTracks'> & {
  captionTracks: { languageCode: string; name: string; isAutoGenerated: boolean }[];
};

export type GetTranscriptResponse =
  | {
      ok: true;
      video: VideoSummary;
      transcript: Transcript | null;
      attempts: TranscriptAttempt[];
      fixture?: TranscriptFixture;
    }
  | { ok: false; error: string };

export interface GenerateQuizMessage {
  type: 'quiz:generate';
  video: Pick<VideoInfo, 'videoId' | 'title' | 'channelName' | 'durationSec'>;
  segments: TranscriptSegment[];
  /** Ignore the cached activities and generate new ones. */
  force?: boolean;
}

export type GenerateQuizResponse =
  | { ok: true; quiz: CachedActivities; cached: boolean }
  | { ok: false; code: QuizErrorCode; error: string };

export interface AskQuestionMessage {
  type: 'video:ask';
  video: Pick<VideoInfo, 'videoId' | 'title' | 'channelName' | 'durationSec'>;
  segments: TranscriptSegment[];
  /** The conversation so far, ending with the new question. */
  turns: ChatTurn[];
}

export type AskQuestionResponse =
  { ok: true; answer: string } | { ok: false; code: QuizErrorCode; error: string };

/** Opens the question dialog on the video. */
export interface OpenAskMessage {
  type: 'ask:open';
}

export interface TestProviderMessage {
  type: 'provider:test';
}

export type TestProviderResponse =
  { ok: true; models: string[] } | { ok: false; code: QuizErrorCode; error: string };

export interface VideoInfoMessage {
  type: 'video:info';
}

export type VideoInfoResponse =
  | { ok: true; video: VideoSummary; eligibility: Eligibility; rule: ChannelRule }
  | { ok: false; error: string };

export interface OpenQuizMessage {
  type: 'quiz:open';
}

export interface QuizStatusMessage {
  type: 'quiz:status';
}

export interface GetCachedQuizMessage {
  type: 'quiz:get-cached';
  videoId: string;
}

export interface OpenOptionsMessage {
  type: 'options:open';
}

export interface RecordResultMessage {
  type: 'activity:record';
  result: VideoResult;
}

export type RecordResultResponse = { ok: true } | { ok: false; error: string };

/** Sent after the dashboard records reviews, so the toolbar badge shows the new due count. */
export interface RefreshBadgeMessage {
  type: 'badge:refresh';
}

const hasType =
  <T extends { type: string }>(type: T['type']) =>
  (message: unknown): message is T =>
    (message as { type?: unknown } | null)?.type === type;

export const isVideoInfoMessage = hasType<VideoInfoMessage>('video:info');
export const isOpenQuizMessage = hasType<OpenQuizMessage>('quiz:open');
export const isOpenAskMessage = hasType<OpenAskMessage>('ask:open');
export const isAskQuestionMessage = hasType<AskQuestionMessage>('video:ask');
export const isQuizStatusMessage = hasType<QuizStatusMessage>('quiz:status');
export const isGetCachedQuizMessage = hasType<GetCachedQuizMessage>('quiz:get-cached');
export const isOpenOptionsMessage = hasType<OpenOptionsMessage>('options:open');
export const isRecordResultMessage = hasType<RecordResultMessage>('activity:record');
export const isRefreshBadgeMessage = hasType<RefreshBadgeMessage>('badge:refresh');

export function isGetTranscriptMessage(message: unknown): message is GetTranscriptMessage {
  return (message as GetTranscriptMessage | null)?.type === 'transcript:get';
}

export function isGenerateQuizMessage(message: unknown): message is GenerateQuizMessage {
  return (message as GenerateQuizMessage | null)?.type === 'quiz:generate';
}

export function isTestProviderMessage(message: unknown): message is TestProviderMessage {
  return (message as TestProviderMessage | null)?.type === 'provider:test';
}
